D3D11  support
wolfpld/tracy pull request #181
Opened 2021-02-23 14:15 UTC by neortls007idev

I was in urgent need of D3D11 support for my program so I decided to fork https://github.com/wolfpld/tracy/pull/88 and made some minor changes like fixing the D3D11 Tracy macros for ZonedScope, Creation and Destruction of the Context and renaming the classes for consistency with D3D12 implementation.

2021-02-23 14:42 UTC, wolfpld requested changes
The manual has to be updated to explain how all this should be used.

2021-02-23 14:42 UTC, wolfpld commented on common/TracyQueue.hpp
> +    Direct3D11
The `GpuContextNames` table in `TracyView.cpp` is not updated.

2021-02-23 14:42 UTC, wolfpld commented on Tracy.hpp
> +
This should be removed.

2021-02-23 14:42 UTC, wolfpld commented on CMakeLists.txt
> +endif()
This should be removed.

2021-02-23 14:44 UTC, neortls007idev commented
Thanks will fix them all in 48 hours.

2021-02-23 15:11 UTC, wolfpld commented on CMakeLists.txt
> +endif()
(By "this" I mean the entire file.)

2021-02-23 19:25 UTC, neortls007idev commented
@wolfpld not sure what the capstone.h file is for and I think it comes from vcpkg as far as I could tell after testing for build on my local machine. Can you shed some light on why the build fails there?

2021-02-23 20:02 UTC, wolfpld commented
Please ignore the failed MSVC build. There were incompatible changes in vcpkg _again_.

2021-02-24 06:23 UTC, neortls007idev commented
There are certain things I haven't had the time to test like tracking multiple deferred contexts or even immediate context migration over multiple threads. So, Should I mention that as a note or something ?  Also the context Owner thread is never shown but in my case I know the my main thread owns it so I am not sure if this is something that should be mentioned in the manual documentation. 
![Tracy](https://user-images.githubusercontent.com/20137351/108956880-15252700-7636-11eb-9c64-91e0d262b026.png)

2021-02-24 11:52 UTC, wolfpld commented
All the shortcomings should be described in the manual. As for the lack of displayed thread, you need to make sure proper thread identifiers are set in the GPU context creation message and all subsequent GPU zone messages, and that it is handled properly server-side. There are two modes of operation for GPU context, one is single-threaded (used for example in OpenGL), and the second is multithreaded (used for example in Vulkan). Maybe you are using the `TRACY_D3D11_NO_SINGLE_THREAD` define incorrectly (I don't know what it is for)?

https://github.com/wolfpld/tracy/blob/c12de1b/server/TracyWorker.cpp#L5303-L5315
https://github.com/wolfpld/tracy/blob/c12de1b/server/TracyView.cpp#L2922

2021-02-24 15:56 UTC, neortls007idev commented
I might need to dig deeper on how it works first, since my goal at the moment was just making it work and being able to do basic profiling and fixing whatever issues the pull request had in it to make it work.

2021-05-02 00:47 UTC, closed without merging